name: C/C++ CI

on:
  pull_request:
    branches: [ " main " ]
    types: [opened, reopened, synchronize]
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: make tests
      run: make tests
    - name: Run response tests
      run: make test/response_test
      
